version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "TwilioAccountIDSIDSecretName=\"TWILIO_ACCOUNT_SID\" TwilioAccessTokenSecretName=\"TWILIO_AUTH_TOKEN\" GoogleAPIKeySecretName=\"GOOGLE_API_KEY\""
